### ISSUE TITLE
./autogen.sh fails with "aclocal: couldn't open directory `m4': No such file or directory"

### ISSUE THREAD

**Issue by clupprich** [lampeh/libvmod-geoip#1]
When cloning the repository and doing a ./autogen.sh on the clean code, it fails with

```
aclocal: couldn't open directory `m4': No such file or directory
```

Any hints?

**Comment by lampeh** [comment]
Indeed, the empty m4 directory wasn't commited. I added m4/.gitignore that will keep the directory but ignore all files inside. Thanks for the report!

Hauke
