### ISSUE TITLE
compiler problem

### ISSUE THREAD

**Issue by redbox-cdn** [lampeh/libvmod-geoip#6]
hi 

I tried install this vmods for varnish3.0.4 (source) on Centos6,

But error message is displayed after following commands.
## COMMAND

./configure VARNISHSRC=/root/src/varnish-3.0.4 VMODDIR=/usr/local/varnish/lib/varnish/vmods
## ERROR MESSAGE

++++++++++++++++++++++++++++++++++++++++++++++

checking for libGeoIP... configure: error: Package requirements (geoip) were not met:
No package 'geoip' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libGeoIP_CFLAGS
and libGeoIP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
++++++++++++++++++++++++++++++++++++++++++++++

I already installed geoip-devel and geoip using yum. and  I can use the geoip lookup command.

Please advice me.

Regards.

Ashly

**Comment by mknwebsolutions** [comment]
Same issue here.  The library is looking for geoip rather GeoIP
